# Usage:
#   just build-target aarch64
#   just build-target armv7
#   just build-target i686
#   just build-target x86_64
#   just build-target all


build-target target:
    if [ "{{target}}" = "aarch64" ] || [ "{{target}}" = "all" ]; then
    cargo build --target aarch64-linux-android --release
    fi

    if [ "{{target}}" = "armv7" ] || [ "{{target}}" = "all" ]; then
    cargo build --target armv7-linux-androideabi --release
    fi

    if [ "{{target}}" = "i686" ] || [ "{{target}}" = "all" ]; then
    cargo build --target i686-linux-android --release
    fi

    if [ "{{target}}" = "x86_64" ] || [ "{{target}}" = "all" ]; then
    cargo build --target x86_64-linux-android --release
    fi


test:
    cargo build --target armv7-linux-androideabi --release

test2:
    ORT_LIB_LOCATION=../onnxruntime/build/Android/Debug  cargo build --target armv7-linux-androideabi

test3:
    ORT_LIB_LOCATION=../onnxruntime/build/Android/Debug  cargo build --target i686-linux-android