// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppPersonalization = { theme: string | null, language: string | null, firstName: string | null, lastName: string | null, email: string | null, preferredVoice: string | null, };
