// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioBook } from "./AudioBook";

export type AudioLibrary = { audioBooks: Array<AudioBook>, };
