// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CachedUser = { identifier: string, firstName: string | null, lastName: string | null, email: string | null, avatarUrl: string | null, };
