// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Events = "processing-audio" | "finished-processing-audio" | "currently-playing-audio";
