[package]
name = "aers_audify"
description = "convert PDF to audio files"
version = "0.1.0"
edition = "2024"


[dependencies]
espeak-rs-sys = "0.1.9"
# extractous = "0.3.0"
piper-rs = {path = "../../../../piper-rs"}
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
