// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioBookEntity = { identifier: string, name: string, src: string, userIdentifier: string, playlistIdentifier: string, createdAt: date, updatedAt: date, lastPlayed: date, };
