// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaginatedResponse<T> = { data: T, page: number, perPage: number, totalCount: bigint, totalPages: number, };
