// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./notification.d";

export type PaginatedNotification = { notifications: Array<Notification>, total: bigint, };
