// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Playlist = { identifier: string, user_identifier: string, name: string, description: string, is_deleted: boolean, created_at: string, updated_at: string, };
