// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserDto = { identifier: string, email: string, firstName: string, lastName: string, profilePicture: string | null, };
