// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserEntity = { email: string, identifier: string, firstName: string | null, lastName: string | null, password: string, isActive: boolean, profilePicture: string | null, username: string | null, };
