/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/button/AppButton.vue')['default']
    AppButtonLink: typeof import('./src/components/button/AppButtonLink.vue')['default']
    AppDock: typeof import('./src/components/uiBlocks/AppDock.vue')['default']
    AppDockPlayer: typeof import('./src/components/uiBlocks/AppDockPlayer.vue')['default']
    AppFormLabel: typeof import('./src/components/form/AppFormLabel.vue')['default']
    AppH1: typeof import('./src/components/typgraphy/AppH1.vue')['default']
    AppHeader: typeof import('./src/components/uiBlocks/AppHeader.vue')['default']
    AppLabeledIcon: typeof import('./src/components/uiBlocks/AppLabeledIcon.vue')['default']
    AppLoader: typeof import('./src/components/uiBlocks/AppLoader.vue')['default']
    AppLogo: typeof import('./src/components/uiBlocks/AppLogo.vue')['default']
    AppNavigation: typeof import('./src/components/uiBlocks/AppNavigation.vue')['default']
    AudioBook: typeof import('./src/components/AudioBook.vue')['default']
    AudioBookCard: typeof import('./src/components/AudioBookCard.vue')['default']
    AudioMotion: typeof import('./src/components/AudioMotion.vue')['default']
    AuthScreenHeaderText: typeof import('./src/components/auth/AuthScreenHeaderText.vue')['default']
    ErrorOutlet: typeof import('./src/components/form/ErrorOutlet.vue')['default']
    FormLoader: typeof import('./src/components/form/FormLoader.vue')['default']
    PlayListModal: typeof import('./src/components/PlayListModal.vue')['default']
    PlayListTag: typeof import('./src/components/PlayListTag.vue')['default']
    ProcessingState: typeof import('./src/components/states/ProcessingState.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensationalTint: typeof import('./src/components/uiBlocks/SensationalTint.vue')['default']
    SubmitButton: typeof import('./src/components/form/SubmitButton.vue')['default']
    Swap: typeof import('./src/components/Swap.vue')['default']
    TogglePlayPause: typeof import('./src/components/player/TogglePlayPause.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    VueGreetings: typeof import('./src/components/uiBlocks/VueGreetings.vue')['default']
  }
}
