/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/button/AppButton.vue')['default']
    AppButtonLink: typeof import('./src/components/button/AppButtonLink.vue')['default']
    AppDock: typeof import('./src/components/uiBlocks/AppDock.vue')['default']
    AppDockPlayer: typeof import('./src/components/uiBlocks/AppDockPlayer.vue')['default']
    AppFormLabel: typeof import('./src/components/form/AppFormLabel.vue')['default']
    AppH1: typeof import('./src/components/typgraphy/AppH1.vue')['default']
    AppHeader: typeof import('./src/components/uiBlocks/AppHeader.vue')['default']
    AppLabeledIcon: typeof import('./src/components/uiBlocks/AppLabeledIcon.vue')['default']
    AppLoader: typeof import('./src/components/uiBlocks/AppLoader.vue')['default']
    AppLogo: typeof import('./src/components/uiBlocks/AppLogo.vue')['default']
    AppModal: typeof import('./src/components/uiBlocks/AppModal.vue')['default']
    AppNavigation: typeof import('./src/components/uiBlocks/AppNavigation.vue')['default']
    AppScreenLayout: typeof import('./src/components/layouts/AppScreenLayout.vue')['default']
    AudioBook: typeof import('./src/components/AudioBook.vue')['default']
    AudioBookCard: typeof import('./src/components/AudioBookCard.vue')['default']
    AudioMotion: typeof import('./src/components/AudioMotion.vue')['default']
    AuthScreenHeaderText: typeof import('./src/components/auth/AuthScreenHeaderText.vue')['default']
    ErrorOutlet: typeof import('./src/components/form/ErrorOutlet.vue')['default']
    FormLoader: typeof import('./src/components/form/FormLoader.vue')['default']
    LabledIcon: typeof import('./src/components/settings/LabledIcon.vue')['default']
    NotificationCard: typeof import('./src/components/notifications/NotificationCard.vue')['default']
    PlayListTag: typeof import('./src/components/PlayListTag.vue')['default']
    ProcessingState: typeof import('./src/components/states/ProcessingState.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLabel: typeof import('./src/components/settings/SectionLabel.vue')['default']
    SensationalTint: typeof import('./src/components/uiBlocks/SensationalTint.vue')['default']
    SubmitButton: typeof import('./src/components/form/SubmitButton.vue')['default']
    TogglePlayPause: typeof import('./src/components/player/TogglePlayPause.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UChip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UserCard: typeof import('./src/components/settings/UserCard.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    VueGreetings: typeof import('./src/components/uiBlocks/VueGreetings.vue')['default']
  }
}
