
services:
  app:
    container_name: aers
    build:
      context: .
      dockerfile: docker/${ENVIRONMENT}/Dockerfile
      args:
        - CARGO_TARGET_DIR=/cargo-target
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      database: 
        condition: service_healthy
    networks:
      - internal
    volumes:
      - .:/app:cached
      - cargo-target:/cargo-target:delegated
      - rust-cache:/usr/local/cargo/registry:delegated
    command: cargo watch -qcx run 
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s  # Wait 30 seconds before starting health checks

  database:
    image: postgres:15-alpine 
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "6543:5432"
    networks:
      - internal
    volumes:
      - postgres-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aers.com
      PGADMIN_DEFAULT_PASSWORD: aers
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  cargo-target:
  rust-cache:
  pgadmin-data:
  redis-data:
  postgres-data:

networks:
  internal:
   name: aers_internal
