name: fuzzing-needswork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    uses: ./.github/workflows/workflow-for-fuzzing-build.yml

  fuzzing-needswork:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        lang: [am, ar, as, az, bn, ca, da, gu, hi, id, kl, kok, ku, lt, mk, ml, mr, ms, my, nog, pt, ro, shn, si, smj, ta, th, tk, tn, tt, ur, vi]
    uses: ./.github/workflows/workflow-for-fuzzing.yml
    with:
      lang: ${{ matrix.lang }}
