name: fuzzing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    uses: ./.github/workflows/workflow-for-fuzzing-build.yml

  fuzzing:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        lang: [af, an, ba, be, bg, bpy, bs, chr, cmn, cs, cv, cy, de, el, en, eo, es, et, eu, fa, fi, fr, ga, gd, gn, grc, hak, haw, he, hr, ht, hu, hy, hyw, ia, io, is, it, ja, jbo, ka, kk, kn, ko, ky, la, lb, lfn, ltg, lv, mi, mt, mto, nb, nci, ne, nl, om, or, pa, pap, piqd, pl, pt-BR, py, qdb, qu, quc, qya, ru, ru-LV, sd, sjn, sk, sl, sq, sr, sv, sw, te, tr, ug, uk, uz, yue]
    uses: ./.github/workflows/workflow-for-fuzzing.yml
    with:
      lang: ${{ matrix.lang }}
