// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { identifier: string, subject: string, body: string, createdAt: string, updatedAt: string, isRead: boolean, userIdentifier: string, };
