// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfile = { identifier: string, email: string, firstName: string | null, lastName: string | null, profilePicture: string | null, };
