name: Build LAME on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - release


jobs:
  build-lame:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            gcc
            make
            automake
            libtool
            nasm

      - name: Build LAME
        shell: msys2 {0}
        run: |
          cd lame
          ./configure --disable-shared --enable-static --enable-nasm --prefix=$(pwd)/../app/src-tauri/sidecar/lame
          make
          make install

      - name: Copy built LAME binary to sidecar
        shell: bash
        run: |
          mkdir -p app/src-tauri/sidecar/binaries
          cp app/src-tauri/sidecar/lame/bin/lame.exe app/src-tauri/sidecar/binaries/lame-$(rustc -Vv | grep host | cut -f2 -d' ')
